- src/components/LoginField.js
- src/components/LogoBigger.js
- src/pages/LoginPage.js
> :lipstick: 로그인페이지 UI

- package.json
- src/components/Board/BoardItem.js
- src/components/Board/BoardList.js
- src/components/Board/Search.js
- src/components/Board/WriteFormContainer.js
- src/components/Board/fileUpload.js
- src/components/Board/pagination.js
- src/pages/QnAPage.js
- yarn.lock
> :lipstick: 글목록 페이지 레이아웃 추가

- src/components/Board/GalleryItem.js
- src/components/Board/Paginations.js
- src/components/Board/fileUpload.js
- src/pages/QnAPage.js
> :memo: 레이아웃 수정

- src/components/Board/BoardList.js
- src/components/Board/CategorySelect.js
- src/components/Board/GalleryContainer.js
- src/components/Board/GalleryItem.js
- src/components/Board/Paginations.js
- src/components/Board/Search.js
- src/components/Board/SubmitButton.js
- src/components/Board/TagInput.js
- src/components/Board/Thumbnail.js
- src/components/Board/Title.js
- src/components/Board/WriteButton.js
- src/pages/BestPage.js
- src/pages/InformationPage.js
- src/pages/PortfolioPage.js
- src/pages/QnAPage.js
- src/pages/WorkerPage.js
> :art: BoardComponent 수정

- src/components/Board/CommentItem.js
- src/components/Board/EditButton.js
- src/components/Board/LikeButton.js
- src/pages/PostDetailPage.js
> :green_heart: PostDetailPage 수정, 삭제버튼 추가

- src/App.js
- src/api/BoardAxiosApi.js
- src/components/Board/BoardList.js
- src/components/Board/GalleryContainer.js
- src/components/Board/GalleryItem.js
- src/components/Board/PostInfo.js
- src/components/Board/SubmitButton.js
- src/pages/PortfolioPage.js
- src/pages/WritePage.js
> :white_check_mark: 포트폴리오 글목록 불러오기

- src/components/Header.js
- src/components/Navbar.js
> :memo: 메인에서 게시판 가는 path 수정

- src/App.js
- src/api/BoardAxiosApi.js
- src/components/Board/BoardList.js
- src/components/Board/CommentForm.js
- src/components/Board/CommentItem.js
- src/components/Board/CommentList.js
- src/components/Board/GalleryItem.js
- src/components/Board/LikeButton.js
- src/components/Board/PostContent.js
- src/components/Board/PostInfo.js
- src/components/Board/Search.js
- src/components/Board/TagList.js
- src/pages/PostDetailPage.js
> :rocket: 상세글 불러오기

- src/api/BoardAxiosApi.js
- src/components/Board/BoardList.js
- src/components/Board/CommentItem.js
- src/components/Board/PostContent.js
- src/components/Board/Search.js
- src/pages/BestPage.js
- src/pages/InformationPage.js
- src/pages/PostDetailPage.js
> :zap: 상세글 본문 이미지 추가

- src/api/BoardAxiosApi.js
- src/components/Board/PostContent.js
> :bug: 상세글보기 오류 수정

- src/App.js
- src/components/Account/ResetPassword.js
- src/pages/ResetPwdPage.js
> :construction: 비밀번호 변경 페이지 UI 1차 완성

- src/components/Board/PostContent.js
- src/pages/PostDetailPage.js
> :ambulance: 글 상세보기 이미지

- src/components/Board/ReplyBoard.js
- src/components/Board/ReplyForm.js
- src/pages/PostDetailPage.js
> :white_check_mark: 댓글 작성 기능 추가

- src/components/Main/BoardItem.js
- src/pages/PostDetailPage.js
> :construction_worker: 글 작성자만 수정, 삭제버튼 

- src/components/Board/ReplyBoard.js
- src/components/Board/ReplyItem.js
> :speech_balloon: 댓글 수정, 삭제 완료

- src/App.js
- src/api/AccountAxiosApi.js
- src/components/Account/AccountPagination.js
- src/components/Account/MemberInformation.js
- src/components/Account/MemberLatestPost.js
- src/components/Account/MemberLatestReply.js
- src/components/Account/MemberTotalPost.js
- src/components/Account/MemberTotalReply.js
- src/components/Account/MyPageMain.js
- src/pages/MyProfilePage.js
- src/util/AccountPopUp.jsx
> :sparkles: 마이페이지 > 나의게시글/댓글 관리 완성

- src/api/BoardAxiosApi.js
- src/components/Board/BoardList.js
- src/components/Board/LikeButton.js
- src/components/Board/Paginations.js
- src/components/Board/Search.js
- src/pages/BestPage.js
- src/pages/InformationPage.js
- src/pages/PostDetailPage.js
- src/pages/QnAPage.js
- src/pages/WorkerPage.js
> :white_check_mark: 게시판 검색기능, 페이징 완료

- src/api/BoardAxiosApi.js
- src/components/Board/BoardList.js
- src/components/Board/Paginations.js
- src/components/Board/Search.js
- src/pages/BestPage.js
- src/pages/InformationPage.js
- src/pages/QnAPage.js
- src/pages/WorkerPage.js
but 검색결과 페이지 넘기면 목록이 자동 렌더링이 안되고 검색버튼을 한번 더 눌러야해서..!! 
이부분 나중에 수정예정..
> :bug: 검색결과 페이징 문제 1차 해결

- src/api/BoardAxiosApi.js
- src/components/Board/LikeButton.js
- src/components/Board/ReplyBoard.js
- src/pages/PostDetailPage.js
- src/util/EditPopUp.jsx
> :rocket: 게시글 추천기능 완료

- src/api/AccountAxiosApi.js
- src/components/Account/MemberEditInformation.js
> :construction: 회원정보 수정 UI 1차 완료

- src/util/EditPopUp.jsx
게시글 삭제 안되는 문제 해결..인데 백앤드 올릴걸 잘못올린
> :bug: 게시글 삭제 안되는 문제 해결

- src/api/AccountAxiosApi.js
- src/components/Account/MemberEditInformation.js
프사 수정 후 로그아웃-> 로그인해야 수정한 프사 적용됨. + firebase storageBucket에 주소를 직접 넣어줘야 돌아가는 상태
> :construction: 프로필사진 업로드 & 변경 구현 1차

- src/api/AccountAxiosApi.js
- src/components/Account/JoinNewMemberInfo.js
- src/components/Account/MemberEditInformation.js
- src/components/Account/MyPageMain.js
- src/components/Account/Wrappers.js
> :construction: 회원정보 수정 조금 완료..

- src/api/BoardAxiosApi.js
- src/components/Board/Category.js
- src/components/Board/WriteForm.js
> :white_check_mark: 글작성 카테고리 권한 설정

- src/components/Account/FindAccount.js
- src/components/Account/JoinCompleteMessage.js
> 임시 비밀번호 발급 기능

- src/components/Account/MemberEditInformation.js
- src/components/Account/MemberInformation.js
프로필사진은 UserInfo context사용 / 수정 후 렌더링은 의존성배열에 memberInfo 추가
> :zap: 회원정보 수정 후 바로 렌더링되도록 수정

- src/components/Board/BoardList.js
- src/components/Board/Category.js
- src/components/Board/EditButton.js
- src/components/Board/GalleryContainer.js
- src/components/Board/GalleryItem.js
- src/components/Board/LikeButton.js
- src/components/Board/Paginations.js
- src/components/Board/PostContent.js
- src/components/Board/PostInfo.js
- src/components/Board/ReplyForm.js
- src/components/Board/Search.js
- src/components/Board/WriteButton.js
- src/components/Board/WriteForm.js
- src/pages/BestPage.js
- src/pages/EditPage.js
- src/pages/InformationPage.js
- src/pages/PostDetailPage.js
- src/pages/QnAPage.js
- src/pages/WorkerPage.js
> :lipstick: 게시판 모바일 버전 UI 수정

- src/components/Board/EditButton.js
- src/components/Board/LikeButton.js
- src/components/Board/WriteButton.js
- src/pages/EditPage.js
- src/pages/PostDetailPage.js
- src/util/EditPopUp.jsx
> :ambulance: 추천 아이콘 위치, 수정시 카테고리 불러오기

- src/api/AccountAxiosApi.js
- src/components/Account/Login.js
> :construction: 로그인시 회원 계정 상태 확인 기능

- src/components/Account/Login.js
- src/components/Account/MemberEditInformation.js
- src/components/Account/MyPageMain.js
- src/context/UserInfo.js
UserInfo.js 파일에 isWithdrawn, setIsWithdrawn 추가,
일단 팝업 대신 alert로..
> :children_crossing: 회원 탈퇴 후 로그아웃 기능

- src/components/Board/BoardList.js
- src/components/Board/GalleryContainer.js
- src/components/Board/GalleryItem.js
- src/components/Board/Paginations.js
- src/components/Board/ReplyForm.js
- src/components/Board/Search.js
- src/components/Board/WriteButton.js
- src/pages/BestPage.js
- src/pages/InformationPage.js
- src/pages/PortfolioPage.js
- src/pages/QnAPage.js
- src/pages/WorkerPage.js
> :green_heart: 게시판 UI 수정

- src/components/Board/BoardList.js
- src/pages/EditPage.js
- src/pages/InformationPage.js
> :bug: 반응형 ui 게시판  정렬 수정, 게시글 수정 태그 업데이트 추가

- src/components/Account/Accordion.js
- src/components/Account/EditProfileImage.js
- src/components/Account/FindAccount.js
- src/components/Account/JoinAgreement.js
- src/components/Account/MemberEditInformation.js
- src/components/Account/MemberInformation.js
> :lipstick: 회원정보 수정 페이지 UI 수정

- src/components/Account/MemberLatestReply.js
memberReply.postNum -> memberReply.replyNum 으로 수정
> :bug: 마이페이지 최근 댓글 5개 key값 수정

- src/components/Board/BoardList.js
- src/components/Board/Paginations.js
- src/pages/BoardPage.js
- src/pages/PortfolioPage.js
- src/pages/WritePage.js
> :bug: 게시판 페이지 정렬 및 자잘한 수정

- src/components/Board/Category.js
- src/components/Board/ContentField.js
- src/components/Board/EditButton.js
- src/components/Board/ImageUpload.js
- src/components/Board/LikeButton.js
- src/components/Board/PostContent.js
- src/components/Board/PostInfo.js
- src/components/Board/ReplyItem.js
- src/components/Board/SearchField.js
- src/components/Board/TagField.js
- src/components/Board/TitleField.js
- src/components/Board/WriteForm.js
- src/pages/BoardPage.js
- src/pages/EditPage.js
- src/pages/PostDetailPage.js
- src/pages/WorkerPage.js
> :bug: css 수정

- src/components/Board/ReplyItem.js
- src/pages/EditPage.js
- src/pages/PostDetailPage.js
> :bug: 댓글 삭제 팝업 수정

- src/components/Board/Category.js
- src/components/Board/ImageUpload.js
- src/pages/EditPage.js
> :green_heart: 게시판 카테고리 css 수정

- src/components/Board/ImageUpload.js
- src/components/Board/WriteForm.js
- src/pages/EditPage.js
> 게시글 이미지 업로드 최종 수정

- src/components/Board/BoardList.js
- src/components/Board/Category.js
- src/components/Board/EditButton.js
- src/components/Board/GalleryContainer.js
- src/components/Board/ImageUpload.js
- src/components/Board/LikeButton.js
- src/components/Board/ReplyItem.js
- src/components/Board/SearchField.js
- src/components/Board/TagList.js
- src/components/Board/WriteForm.js
- src/pages/BoardPage.js
- src/pages/PostDetailPage.js
> :memo: 게시판 코드 정리

- src/api/BoardAxiosApi.js
- src/components/Board/ContentField.js
- src/components/Board/GalleryContainer.js
- src/components/Board/GalleryItem.js
- src/components/Board/ImageUpload.js
- src/components/Board/TagField.js
- src/components/Board/TitleField.js
- src/pages/EditPage.js
- src/pages/PostDetailPage.js
> :lipstick: 게시판 반응형 수정

- src/pages/EditPage.js
- src/pages/PortfolioPage.js
- src/pages/PostDetailPage.js
> :bug: 수정페이지 이미지 문제 해결

- src/pages/PortfolioPage.js
> :lipstick: 포트폴리오 페이지 css  수정

- src/components/Board/EditButton.js
- src/components/Board/ImageUpload.js
- src/components/Board/PostContent.js
- src/components/Board/SearchField.js
- src/components/Board/WriteForm.js
- src/pages/BoardPage.js
- src/pages/EditPage.js
- src/pages/PostDetailPage.js
> :lipstick: css 수정
